/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package br.com.projeto_10.view;

import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import br.com.projeto_10.dto.FuncionarioDTO;

import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;
/**
 *
 * @author gusta
 */
public class PrincipalVIEW extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalVIEW
     */
    public PrincipalVIEW(FuncionarioDTO funcionarioDTO) {
        initComponents();
        this.setLocationRelativeTo(null);
        if(funcionarioDTO.getTipo_fun().equalsIgnoreCase("FUNCIONARIO")){
            itemMenuFuncionario.setVisible(false);
            
        }
    }

    private void sair() {
        Object[] options = {"Sair", "Cancelar"};
        if (JOptionPane.showOptionDialog(null, "Deseja Sair do Sistema", "Informação",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]) == 0) {
            System.exit(0);
        }
    }

    private void abreAviarioVIEW() {
        AviarioVIEW aviarioVIEW = new AviarioVIEW();
        this.desktopPane.add(aviarioVIEW);
        aviarioVIEW.setVisible(true);
        aviarioVIEW.setPosicao();
    }

    private void abreAdotanteVIEW() {
        CompradorVIEW adotanteVIEW = new CompradorVIEW();
        this.desktopPane.add(adotanteVIEW);
        adotanteVIEW.setVisible(true);
        adotanteVIEW.setPosicao();
    }

    private void abreCanarioVIEW() {
        CanarioVIEW canarioVIEW = new CanarioVIEW();
        this.desktopPane.add(canarioVIEW);
        canarioVIEW.setVisible(true);
        canarioVIEW.setPosicao();
    }

    private void abreVendaVIEW() {
        VendaVIEW vendaVIEW = new VendaVIEW();
        this.desktopPane.add(vendaVIEW);
        vendaVIEW.setVisible(true);
        vendaVIEW.setPosicao();
    }
    
    private void abreFuncionarioVIEW(){
        FuncionarioVIEW funcionarioVIEW = new FuncionarioVIEW();
        this.desktopPane.add(funcionarioVIEW);
        funcionarioVIEW.setVisible(true);
        funcionarioVIEW.setPosicao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        itemMenuComprador = new javax.swing.JMenuItem();
        itemMenuCachorro = new javax.swing.JMenuItem();
        itemMenuAviario = new javax.swing.JMenuItem();
        itemMenuProduto = new javax.swing.JMenuItem();
        itemMenuFuncionario = new javax.swing.JMenuItem();
        menuAdocao = new javax.swing.JMenu();
        itemMenuVenda = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCadastro.setMnemonic('f');
        menuCadastro.setText("Cadastro");

        itemMenuComprador.setMnemonic('o');
        itemMenuComprador.setText("Comprador");
        itemMenuComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCompradorActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuComprador);

        itemMenuCachorro.setMnemonic('x');
        itemMenuCachorro.setText("Canario");
        itemMenuCachorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCachorroActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuCachorro);

        itemMenuAviario.setMnemonic('s');
        itemMenuAviario.setText("Aviario");
        itemMenuAviario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAviarioActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuAviario);

        itemMenuProduto.setText("Produto");
        itemMenuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuProdutoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuProduto);

        itemMenuFuncionario.setMnemonic('a');
        itemMenuFuncionario.setText("Funcionário");
        itemMenuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuFuncionarioActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuFuncionario);

        menuBar.add(menuCadastro);

        menuAdocao.setMnemonic('e');
        menuAdocao.setText("Custos");

        itemMenuVenda.setMnemonic('t');
        itemMenuVenda.setText("Venda");
        itemMenuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVendaActionPerformed(evt);
            }
        });
        menuAdocao.add(itemMenuVenda);

        menuBar.add(menuAdocao);

        menuSair.setMnemonic('h');
        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        menuBar.add(menuSair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuCachorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCachorroActionPerformed
        abreCanarioVIEW();
    }//GEN-LAST:event_itemMenuCachorroActionPerformed

    private void itemMenuCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCompradorActionPerformed
        abreAdotanteVIEW();
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuCompradorActionPerformed

    private void itemMenuAviarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAviarioActionPerformed
        abreAviarioVIEW();
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuAviarioActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        sair();
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSairMouseClicked

    private void itemMenuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuProdutoActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuProdutoActionPerformed

    private void itemMenuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVendaActionPerformed
        abreVendaVIEW();
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuVendaActionPerformed

    private void itemMenuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuFuncionarioActionPerformed
        abreFuncionarioVIEW();
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem itemMenuAviario;
    private javax.swing.JMenuItem itemMenuCachorro;
    private javax.swing.JMenuItem itemMenuComprador;
    private javax.swing.JMenuItem itemMenuFuncionario;
    private javax.swing.JMenuItem itemMenuProduto;
    private javax.swing.JMenuItem itemMenuVenda;
    private javax.swing.JMenu menuAdocao;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables

}
